(() => {
  const ENDPOINT='https://dbwnvbfdphqmfjzbpqnw.supabase.co/functions/v1/orlica-admin';
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const token=()=>localStorage.getItem('orlica_admin_token')||'';
  async function call(action,data={}){const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','x-admin-token':token()},body:JSON.stringify({action,...data})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Ошибка');return j}
  function shell(){
    const app=document.querySelector('#app'); if(!app||document.querySelector('#v101-admin'))return document.querySelector('#v101-admin');
    const sec=document.createElement('section');sec.id='v101-admin';sec.innerHTML=`<div class="v101-admin-head"><div><h2>ОБЪЯВЛЕНИЯ</h2><span>Акции · свободные окна · новости. Изменения сразу появляются на сайте.</span></div><button class="btn dark" id="v101-ann-refresh" type="button">Обновить</button></div><form class="v101-ann-form" id="v101-ann-form"><label>Метка<input name="label" maxlength="40" placeholder="АКЦИЯ / НОВОСТЬ"></label><label>Заголовок<input name="title" maxlength="120" required placeholder="Например: −15% на свободный эскиз"></label><label class="wide">Текст<textarea name="body" maxlength="1500" placeholder="Условия акции или важная информация"></textarea></label><label class="wide">Ссылка<input name="url" maxlength="500" inputmode="url" placeholder="https://t.me/..."></label><button class="btn" type="submit">+ Опубликовать</button></form><div class="v101-ann-list" id="v101-ann-list"></div>`;app.appendChild(sec);sec.querySelector('#v101-ann-refresh').onclick=load;sec.querySelector('#v101-ann-form').onsubmit=submit;return sec;
  }
  function render(items=[]){const root=shell()?.querySelector('#v101-ann-list');if(!root)return;root.innerHTML=items.length?items.map(x=>`<article class="v101-ann ${x.is_active?'':'off'}" data-id="${x.id}"><div class="v101-ann-top"><div><div class="tag">${esc(x.label||'ОБЪЯВЛЕНИЕ')}</div><h3>${esc(x.title)}</h3></div><span class="status">${x.is_active?'на сайте':'скрыто'}</span></div><p>${esc(x.body||'')}</p>${x.url?`<div class="meta">${esc(x.url)}</div>`:''}<div class="v101-ann-actions"><button class="btn dark toggle" type="button">${x.is_active?'Скрыть':'Показать'}</button><button class="btn bad delete" type="button">Удалить</button></div></article>`).join(''):'<div class="empty">Объявлений пока нет.</div>';root.querySelectorAll('[data-id]').forEach(card=>{const item=items.find(x=>x.id===card.dataset.id);card.querySelector('.toggle').onclick=async()=>{try{await call('update_announcement',{id:item.id,is_active:!item.is_active});await load()}catch(e){alert(e.message)}};card.querySelector('.delete').onclick=async()=>{if(!confirm('Удалить объявление?'))return;try{await call('delete_announcement',{id:item.id});await load()}catch(e){alert(e.message)}}})}
  async function submit(e){e.preventDefault();const form=e.currentTarget,fd=new FormData(form),btn=form.querySelector('button[type=submit]');btn.disabled=true;btn.textContent='Публикую…';try{await call('create_announcement',{label:String(fd.get('label')||'').trim(),title:String(fd.get('title')||'').trim(),body:String(fd.get('body')||'').trim(),url:String(fd.get('url')||'').trim(),is_active:true});form.reset();await load()}catch(err){alert(err.message)}finally{btn.disabled=false;btn.textContent='+ Опубликовать'}}
  async function load(){if(!token())return;try{const state=await call('state');render(state.announcements||[])}catch(e){console.warn('announcement admin',e)}}
  function boot(){let tries=0;const t=setInterval(()=>{if(document.querySelector('#app.show')&&token()){clearInterval(t);shell();load()}else if(++tries>120)clearInterval(t)},250)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
