(() => {
  const ENDPOINT='https://dbwnvbfdphqmfjzbpqnw.supabase.co/functions/v1/orlica-admin',TZ='Asia/Yakutsk';
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const fmt=iso=>new Intl.DateTimeFormat('ru-RU',{timeZone:TZ,weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(iso));
  const statusRu=s=>({pending:'ожидает',confirmed:'подтверждено',cancelled:'отменено',completed:'завершено',waiting:'ждёт',contacted:'связались',booked:'записан',open:'свободно'})[s]||s;
  function token(){return localStorage.getItem('orlica_admin_token')||''}
  async function call(action,data={}){const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','x-admin-token':token()},body:JSON.stringify({action,...data})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Ошибка');return j}
  const same=(a,b)=>String(a||'').trim().toLowerCase()===String(b||'').trim().toLowerCase();
  function mountShell(){const app=document.querySelector('#app');if(!app||document.querySelector('#v9-admin'))return null;const s=document.createElement('section');s.id='v9-admin';s.className='v9';s.innerHTML='<div class="v9-head"><div><h2>V9 · КЛИЕНТЫ</h2><span>Переносы · заметки · история · лист ожидания</span></div><button class="btn dark" id="v9-refresh">Обновить</button></div><div id="v9-bookings" class="v9-grid"></div><div class="v9-head" style="margin-top:34px"><div><h2>ЛИСТ ОЖИДАНИЯ</h2><span id="v9-wait-count">0 человек</span></div></div><div id="v9-waitlist" class="v9-grid"></div>';app.appendChild(s);s.querySelector('#v9-refresh').onclick=load;return s}
  function renderBookingCard(b,slots,bookings){const history=bookings.filter(x=>x.id!==b.id&&same(x.contact,b.contact)).slice(0,4);const open=slots.filter(s=>s.status==='open'&&new Date(s.starts_at)>new Date());return `<article class="v9-card" data-bid="${b.id}"><div class="v9-card-top"><div><strong>${esc(b.client_name)}</strong><div class="meta">${esc(b.contact)} · ${esc(b.booking_code)}</div></div><div class="v9-pills"><span class="v9-pill">${statusRu(b.status)}</span><span class="v9-pill">${esc(b.tattoo_place)}</span></div></div><div class="idea">${esc(b.idea)}</div>${b.sketch_url?`<a href="${esc(b.sketch_url)}" target="_blank" rel="noopener" class="meta">Открыть эскиз</a>`:''}<div class="v9-history">История клиента: ${history.length?history.map(h=>`${fmt((slots.find(s=>s.id===h.slot_id)||{}).starts_at||h.created_at)} · ${statusRu(h.status)}`).join('<br>'):'других записей нет'}</div><textarea class="v9-note" placeholder="Заметка Светы">${esc(b.admin_note||'')}</textarea><div class="v9-controls"><select class="v9-slot"><option value="">Перенести на…</option>${open.map(s=>`<option value="${s.id}">${fmt(s.starts_at)} · ${s.duration_minutes} мин</option>`).join('')}</select><button class="btn dark v9-move" type="button">Перенести</button></div><div class="v9-actions"><button class="btn dark v9-save-note" type="button">Сохранить заметку</button></div></article>`}
  function renderWait(w){return `<article class="v9-card v9-wait" data-wid="${w.id}"><div class="v9-card-top"><div><strong>${esc(w.client_name)}</strong><div class="meta">${esc(w.contact)}</div></div><div class="v9-pills"><span class="v9-pill">${statusRu(w.status)}</span>${w.preferred_time?`<span class="v9-pill">${esc(w.preferred_time)}</span>`:''}</div></div><div class="idea">${w.tattoo_place?`<b>${esc(w.tattoo_place)}</b>${w.tattoo_size?' · '+esc(w.tattoo_size):''}<br>`:''}${esc(w.idea)}</div><div class="v9-actions">${w.status==='waiting'?'<button class="btn ok" data-wstatus="contacted">Связались</button>':''}${w.status!=='booked'?'<button class="btn dark" data-wstatus="booked">Записан</button>':''}${w.status!=='cancelled'?'<button class="btn bad" data-wstatus="cancelled">Убрать</button>':''}</div></article>`}
  async function load(){const shell=mountShell();if(!shell||!token())return;try{const {slots,bookings,waitlist=[]}=await call('state');const active=bookings.filter(b=>['pending','confirmed'].includes(b.status));shell.querySelector('#v9-bookings').innerHTML=active.length?active.map(b=>renderBookingCard(b,slots,bookings)).join(''):'<div class="v9-empty">Активных записей нет.</div>';const waiting=waitlist.filter(w=>!['cancelled','booked'].includes(w.status));shell.querySelector('#v9-wait-count').textContent=`${waiting.length} в списке`;shell.querySelector('#v9-waitlist').innerHTML=waiting.length?waiting.map(renderWait).join(''):'<div class="v9-empty">Лист ожидания пуст.</div>';
    shell.querySelectorAll('[data-bid]').forEach(card=>{const id=card.dataset.bid;card.querySelector('.v9-save-note').onclick=async()=>{try{await call('update_booking_note',{id,note:card.querySelector('.v9-note').value});card.querySelector('.v9-save-note').textContent='Сохранено';setTimeout(()=>card.querySelector('.v9-save-note').textContent='Сохранить заметку',900)}catch(e){alert(e.message)}};card.querySelector('.v9-move').onclick=async()=>{const slot=card.querySelector('.v9-slot').value;if(!slot)return alert('Выбери новое окно');if(!confirm('Перенести запись? Старое окно снова станет свободным.'))return;try{await call('transfer_booking',{id,new_slot_id:slot});await load()}catch(e){alert(e.message)}}});
    shell.querySelectorAll('[data-wid]').forEach(card=>card.querySelectorAll('[data-wstatus]').forEach(btn=>btn.onclick=async()=>{try{await call('set_waitlist_status',{id:card.dataset.wid,status:btn.dataset.wstatus});await load()}catch(e){alert(e.message)}}));
  }catch(e){console.warn('V9 admin',e.message)}}
  function boot(){let tries=0;const t=setInterval(()=>{const app=document.querySelector('#app.show');if(app&&token()){clearInterval(t);load()}else if(++tries>120)clearInterval(t)},250)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
