import {useState,useEffect} from 'react';
import {ArrowUpRight,Menu,ArrowDown} from 'lucide-react';
import {Dialog,DialogTrigger,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {Button} from './ui/button';
import {Link,useRouter} from '../router';
import {pages,links,works} from '../data';
import {asset} from '../lib/utils';
export function Layout({children}){const[open,setOpen]=useState(false);const[hover,setHover]=useState(0);const{path}=useRouter();useEffect(()=>setOpen(false),[path]);
return <><a className="skip-link" href="#main">К содержанию</a><header className="site-header"><Link to="/" className="wordmark" aria-label="MALABAR — главная">MALABAR<span>tatt.</span></Link><div className="header-location">ТАТУ-СТУДИЯ · БЛАГОВЕЩЕНСК</div><nav className="desktop-nav" aria-label="Основное меню"><Link to="/works" aria-current={path.startsWith('/works')?'page':undefined}>Работы</Link><Link to="/flash" aria-current={path==='/flash'?'page':undefined}>Эскизы</Link><Link to="/constructor" aria-current={path==='/constructor'?'page':undefined}>Конструктор</Link><Link to="/about" aria-current={path==='/about'?'page':undefined}>Обо мне</Link><Link to="/prices" aria-current={path==='/prices'?'page':undefined}>Цены</Link></nav><Link to="/booking" className="header-book">На сеанс <ArrowUpRight size={17}/></Link><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="ghost" size="icon" aria-label="Открыть меню"><Menu size={23}/></Button></DialogTrigger><DialogContent className="menu-content"><DialogTitle className="menu-label">MALABAR / НАВИГАЦИЯ</DialogTitle><DialogDescription className="sr-only">Выбери страницу сайта</DialogDescription><div className="menu-photo"><img src={asset(`assets/works/${works[hover%works.length].image}`)} alt=""/></div><nav className="overlay-nav">{pages.map(([to,name],i)=><Link key={to} to={to} onMouseEnter={()=>setHover(i)} onFocus={()=>setHover(i)}><small>0{i+1}</small>{name}<ArrowUpRight/></Link>)}</nav><div className="menu-bottom"><a href={links.channel} target="_blank" rel="noreferrer">Telegram ↗</a><a href={links.vk} target="_blank" rel="noreferrer">ВКонтакте ↗</a></div></DialogContent></Dialog></header><main id="main" tabIndex={-1} key={path}>{children}</main><footer className="site-footer"><div className="footer-top"><span>ТВОЯ КОЖА. ТВОЯ ИСТОРИЯ.</span><a href={links.channel} target="_blank" rel="noreferrer">TELEGRAM ↗</a><a href={links.vk} target="_blank" rel="noreferrer">VK ↗</a><span>БЛАГОВЕЩЕНСК</span></div><Link to="/booking" className="footer-cta">ОСТАВИТЬ<br/><i>свой</i> СЛЕД <ArrowUpRight/></Link><div className="footer-bottom"><Link to="/">MALABAR TATT.</Link><Link to="/constructor">Конструктор</Link><Link to="/process">Процесс</Link><Link to="/faq">Вопросы</Link><span>© {new Date().getFullYear()}</span></div></footer></>}
export const Arrow=({size=22})=><ArrowUpRight size={size}/>;
