import {useRef,useState} from 'react';
import {motion,useDragControls} from 'motion/react';
import {DraggableCard} from '../components/aceternity/draggable-card';
import {Button} from '../components/ui/button';
import {RotateCcw,ArrowUpRight,Move} from 'lucide-react';
import {works} from '../data';
import {asset} from '../lib/utils';
import {Link} from '../router';
const workLayout={left:[45,290,555,795,1010],top:[95,260,55,230,85],rotate:[-8,7,-5,9,-7]};
const flashLayout={left:[35,275,520,765,1015,1260,240,720,1160],top:[95,350,55,320,80,365,690,650,685],rotate:[-7,5,-4,8,-6,5,7,-5,6]};

export default function DragGallery({items=works.slice(0,5),variant='works'}){const viewport=useRef();const controls=useDragControls();const[key,setKey]=useState(0);const isFlash=variant==='flash';const layout=isFlash?flashLayout:workLayout;return <><div className="drag-toolbar"><span><Move size={17}/> ДВИГАЙ ЭСКИЗЫ ИЛИ ФОН</span><Button variant="ghost" onClick={()=>setKey(x=>x+1)}><RotateCcw size={16}/> Сначала</Button></div><div className={`drag-viewport ${isFlash?'flash-drag-viewport':''}`} ref={viewport} key={key}><motion.div className={`drag-plane ${isFlash?'flash-drag-plane':''}`} drag dragControls={controls} dragListener={false} dragConstraints={isFlash?{left:-1250,right:90,top:-620,bottom:70}:{left:-750,right:80,top:-250,bottom:60}} dragElastic={.12} onPointerDown={e=>{if(e.target.closest('.draggable-card'))return;controls.start(e)}}><div className="drag-type" aria-hidden="true">{isFlash?<>ТВОЙ<br/><i>эскиз.</i></>:<>ТВОЯ<br/><i>композиция.</i></>}</div>{items.map((item,i)=>{const image=isFlash?`assets/flash/${item.image.replace('.webp','-640.webp')}`:`assets/works/${item.image.replace('.webp','-480.webp')}`;const href=isFlash?'/booking':`/works/${item.slug}`;return <DraggableCard key={item.slug||item.number} className={isFlash?'flash-drag-card':''} dragConstraints={{left:-180,right:190,top:-150,bottom:160}} style={{left:layout.left[i],top:layout.top[i],rotate:layout.rotate[i]}}><img src={asset(image)} alt={isFlash?`${item.title.toLowerCase()}, свободный эскиз`:item.title} draggable="false" width="480" height="640" loading="lazy"/><Link to={href} onPointerDown={e=>e.stopPropagation()}>{item.number} / {isFlash?'ВЫБРАТЬ':'СМОТРЕТЬ'} <ArrowUpRight size={17}/></Link></DraggableCard>})}</motion.div></div><p className="drag-instruction">{isFlash?'Потяни фон или разложи эскизы по-своему. Нажми «Выбрать», чтобы обсудить работу.':'Меняй композицию как хочется. Открой работу кнопкой под фотографией.'}</p></>}
