import {useRef,useEffect,useState} from 'react';
import {RotateCcw,Eye} from 'lucide-react';
import {Button} from '../components/ui/button';
import {asset} from '../lib/utils';
export default function TattooReveal(){const canvas=useRef(null);const api=useRef({});const[ready,setReady]=useState(false);const[failed,setFailed]=useState(false);const[drawing,setDrawing]=useState(false);
useEffect(()=>{const el=canvas.current;const image=new Image();let mask=document.createElement('canvas');let ctx=el.getContext('2d'),mc=mask.getContext('2d');let frame=0,last=null,active=false,ratio=1;let alive=true;
const render=()=>{frame=0;ctx.clearRect(0,0,el.width,el.height);ctx.globalCompositeOperation='source-over';ctx.drawImage(image,0,0,el.width,el.height);ctx.globalCompositeOperation='destination-in';ctx.drawImage(mask,0,0);ctx.globalCompositeOperation='source-over'};
const resize=()=>{ratio=Math.min(devicePixelRatio||1,1.5);const box=el.getBoundingClientRect();el.width=mask.width=Math.round(box.width*ratio);el.height=mask.height=Math.round(box.height*ratio);if(image.complete&&image.naturalWidth)render()};
const dot=(x,y,r)=>{const g=mc.createRadialGradient(x,y,r*.48,x,y,r);g.addColorStop(0,'rgba(0,0,0,1)');g.addColorStop(.7,'rgba(0,0,0,.8)');g.addColorStop(1,'rgba(0,0,0,0)');mc.fillStyle=g;mc.beginPath();mc.arc(x,y,r,0,Math.PI*2);mc.fill()};
const paint=e=>{const b=el.getBoundingClientRect();const p={x:(e.clientX-b.left)*ratio,y:(e.clientY-b.top)*ratio,t:performance.now()};const distance=last?Math.hypot(p.x-last.x,p.y-last.y):0;const speed=last?distance/Math.max(1,p.t-last.t):0;const radius=(28+Math.min(speed*8,20))*ratio;const steps=Math.max(1,Math.ceil(distance/(radius*.3)));for(let i=0;i<=steps;i++){const t=i/steps;dot(last?last.x+(p.x-last.x)*t:p.x,last?last.y+(p.y-last.y)*t:p.y,radius)}last=p;if(!frame)frame=requestAnimationFrame(render)};
const down=e=>{if(!image.complete||!image.naturalWidth)return;active=true;last=null;setDrawing(true);el.setPointerCapture(e.pointerId);paint(e)};const move=e=>{if(active)paint(e)};const up=()=>{active=false;last=null;setDrawing(false)};
image.onload=()=>{if(alive){resize();setReady(true)}};image.onerror=()=>alive&&setFailed(true);image.src=asset('assets/hero/sveta-ink.webp');const observer=new ResizeObserver(resize);observer.observe(el);el.addEventListener('pointerdown',down);el.addEventListener('pointermove',move);el.addEventListener('pointerup',up);el.addEventListener('pointercancel',up);api.current={reset:()=>{mc.clearRect(0,0,mask.width,mask.height);render()},all:()=>{mc.fillStyle='#000';mc.fillRect(0,0,mask.width,mask.height);render()}};
return()=>{alive=false;cancelAnimationFrame(frame);observer.disconnect();el.removeEventListener('pointerdown',down);el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',up);el.removeEventListener('pointercancel',up)}},[]);
return <div className={`tattoo-reveal ${drawing?'is-drawing':''}`}><div className="reveal-frame"><img src={asset('assets/hero/sveta-clean.webp')} alt="Портрет Светы без тату — проведи по нему, чтобы проявить второй слой" width="720" height="980" loading="lazy"/><canvas ref={canvas} aria-label="Рисование: проведи пальцем, чтобы проявить татуировки"/><span className="reveal-corner">INK / ON SKIN</span></div><div className="reveal-controls"><span aria-live="polite">{failed?'Фото не загрузилось':drawing?'ТВОЙ СЛЕД':'ПРИКОСНИСЬ К ФОТО'}</span><Button variant="ghost" size="icon" disabled={!ready} aria-label="Показать все татуировки" onClick={()=>api.current.all?.()}><Eye size={20}/></Button><Button variant="ghost" size="icon" disabled={!ready} aria-label="Стереть следы" onClick={()=>api.current.reset?.()}><RotateCcw size={19}/></Button></div></div>}
