import {lazy,Suspense,useState,useRef,useEffect} from 'react';
import {motion,useScroll,useTransform,useReducedMotion} from 'motion/react';
import {ArrowDown,ArrowUpRight,Plus} from 'lucide-react';
import {Link,useRouter} from './router';
import {BlurFade} from './components/magicui/blur-fade';
import {TextAnimate} from './components/magicui/text-animate';
import {Button} from './components/ui/button';
import {Accordion,AccordionItem} from './components/ui/accordion';
import {WorkImage} from './components/WorkImage';
import {works,links} from './data';
import {asset} from './lib/utils';
const TattooReveal=lazy(()=>import('./scenes/TattooReveal'));
const DragGallery=lazy(()=>import('./scenes/DragGallery'));
export function Home(){const hero=useRef();const reduced=useReducedMotion();const move=e=>{if(reduced||e.pointerType==='touch')return;const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--hx',`${(e.clientX/r.width-.5)*10}px`);e.currentTarget.style.setProperty('--hy',`${((e.clientY-r.top)/r.height-.5)*7}px`)};
return <><section className="hero" ref={hero} onPointerMove={move} onPointerLeave={e=>{e.currentTarget.style.setProperty('--hx','0px');e.currentTarget.style.setProperty('--hy','0px')}}><div className="hero-kicker"><span>АВТОРСКАЯ ТАТУИРОВКА</span><span>НЕЖНОСТЬ С ХАРАКТЕРОМ</span></div><h1 className="hero-title" aria-label="Орлица">{'ОРЛИЦА'.split('').map((l,i)=><span key={i} style={{'--i':i}}>{l}</span>)}</h1><div className="hero-photo-wrap"><img className="hero-photo" src={asset('assets/hero/sveta-clean.webp')} alt="Портрет тату-мастера ORLICA" width="720" height="980" fetchPriority="high"/><span className="portrait-credit">ORLICA / TATTOO ARTIST</span></div><span className="hero-front" aria-hidden="true">tatt.</span><div className="hero-note"><span className="tiny-cross">✳</span><p>Искусство,<br/>которое остаётся<br/><i>с тобой.</i></p></div><Link to="/works" className="hero-explore"><span>СМОТРЕТЬ<br/>РАБОТЫ</span><span className="circle-arrow"><ArrowUpRight size={30}/></span></Link><div className="hero-bottom"><span>ГРАФИКА / ЦВЕТ / ХАРАКТЕР</span><a href="#selected" aria-label="К избранным работам"><ArrowDown size={19}/></a><span>01 — 08</span></div></section><section className="selected-section" id="selected"><div className="section-eyebrow"><span>01 / ИЗБРАННОЕ</span><span>НЕСКОЛЬКО ИСТОРИЙ НА КОЖЕ</span></div><div className="selected-heading"><TextAnimate as="h2">ТОЧНО ТВОЁ.</TextAnimate><p>Тонкая линия.<br/>Смелый цвет.<br/><i>Твой характер.</i></p></div><div className="selected-grid"><BlurFade><WorkImage work={works[0]}/></BlurFade><BlurFade delay={.12}><WorkImage work={works[2]}/></BlurFade></div><Link to="/works" className="text-link all-works">Все работы <ArrowUpRight/></Link></section><section className="reveal-section"><div className="reveal-copy"><span className="eyebrow">02 / ПРИКОСНОВЕНИЕ</span><TextAnimate as="h2">КОЖА. ЧЕРНИЛА. ТЫ.</TextAnimate><p>Проведи пальцем по портрету.<br/>Оставь свой след.</p><span className="reveal-footnote">Визуальный эксперимент</span></div><Suspense fallback={<div className="scene-loading">ОРЛИЦА</div>}><TattooReveal/></Suspense></section></>}
export function Works(){const[filter,setFilter]=useState('Все');const visible=works.filter(w=>filter==='Все'||w.category===filter);return <div className="works-page"><div className="page-heading"><div className="section-eyebrow"><span>ПОРТФОЛИО / 01—08</span><span>ORLICA TATT · БЛАГОВЕЩЕНСК</span></div><TextAnimate>РАБОТЫ.</TextAnimate><div className="heading-bottom"><p>Маленькие детали.<br/><i>Большие чувства.</i></p><div className="filters" aria-label="Фильтр работ">{['Все','Графика','Олдскул','Флористика','Миниатюры','Орнамент'].map(f=><Button variant="ghost" key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}{filter===f&&<span className="filter-dot"/>}</Button>)}</div></div></div><div className={`editorial-grid ${filter!=='Все'?'filtered':''}`}>{visible.map((w,i)=><BlurFade key={w.slug} className={`editorial-item item-${i%8}`}><WorkImage work={w} priority={i===0}/></BlurFade>)}</div><div className="gallery-source"><span>ЕЩЁ БОЛЬШЕ ИСТОРИЙ</span><a href={links.channel} target="_blank" rel="noreferrer">@orlica_tatt <ArrowUpRight/></a></div><section className="play-scene"><div className="section-eyebrow"><span>СВОБОДНАЯ КОМПОЗИЦИЯ</span><span>ДВИГАЙ ФОТО · ОТКРЫВАЙ РАБОТЫ</span></div><Suspense fallback={<div className="scene-loading">РАЗЛОЖИ ПО-СВОЕМУ.</div>}><DragGallery/></Suspense></section></div>}
export function WorkDetail({slug}){const idx=works.findIndex(w=>w.slug===slug);const work=works[idx];const next=works[(idx+1)%works.length];const{navigate}=useRouter();const nextRef=useRef(null);const[auto,setAuto]=useState(true);const reduced=useReducedMotion();const {scrollYProgress}=useScroll({target:nextRef,offset:['start end','end end']});const scale=useTransform(scrollYProgress,[0,1],[.78,1]);
useEffect(()=>{if(!auto||reduced||!work)return;let timer=null;let engaged=false;const arm=()=>{engaged=true};window.addEventListener('wheel',arm,{passive:true});window.addEventListener('touchmove',arm,{passive:true});const observer=new IntersectionObserver(entries=>{clearTimeout(timer);if(entries[0].isIntersecting&&engaged)timer=setTimeout(()=>navigate(`/works/${next.slug}`,{image:next.slug}),1100)},{threshold:1});const sentinel=document.querySelector('.next-sentinel');if(sentinel)observer.observe(sentinel);return()=>{observer.disconnect();clearTimeout(timer);window.removeEventListener('wheel',arm);window.removeEventListener('touchmove',arm)}},[auto,reduced,slug]);
if(!work)return <NotFound/>;return <article className="detail-page"><div className="detail-top"><Link to="/works" className="back-link">← ВСЕ РАБОТЫ</Link><span>{work.number} / 08 · {work.category.toUpperCase()}</span></div><TextAnimate className="detail-title">{work.title}</TextAnimate><div className="detail-art"><WorkImage work={work} priority linked={false}/><span className="detail-side">ORLICA / SELECTED WORK</span></div><div className="detail-description"><a className="eyebrow" href={`https://t.me/orlica_tatt/${work.source}`} target="_blank" rel="noreferrer">{work.category.toUpperCase()} / TELEGRAM ↗</a><p>{work.description}</p><Link to="/booking" className="text-link">Хочу свою историю <ArrowUpRight/></Link></div><section className="next-work" ref={nextRef}><div className="next-label"><span>ДАЛЬШЕ / {next.title}</span><button className="auto-toggle" onClick={()=>setAuto(!auto)} aria-pressed={auto}>{auto?'Автопереход включён':'Автопереход выключен'}</button></div><motion.div style={{scale:reduced?1:scale}}><Link to={`/works/${next.slug}`} shared={next.slug}><img src={asset(`assets/works/${next.image}`)} alt={`Следующая работа — ${next.title}`} width="480" height="640" loading="lazy" data-work={next.slug}/><div className="next-work-title">{next.title}<ArrowUpRight/></div></Link></motion.div><div className="next-sentinel" aria-hidden="true"/></section></article>}
export function About(){return <div className="about-page"><div className="page-heading"><span className="eyebrow">ЗА КАЖДОЙ ЛИНИЕЙ — ЧЕЛОВЕК</span><TextAnimate>ЭТО Я.</TextAnimate></div><div className="about-layout"><BlurFade className="about-portrait"><img src={asset('assets/hero/sveta-portrait.webp')} alt="Тату-мастер в студии" width="720" height="960"/><span>ORLICA TATT / БЛАГОВЕЩЕНСК</span></BlurFade><div className="about-text"><span className="tiny-cross">✳</span><h2>Графика,<br/><i>нежнятина</i><br/>и странные звери.</h2><p>Я работаю в студии Malabar и создаю авторские татуировки. Люблю выразительные линии, необычных персонажей и идеи с характером.</p><p>Приходи со своей задумкой. Обсудим, как превратить её в рисунок, который будет твоим.</p><Link to="/booking" className="text-link">Давай знакомиться <ArrowUpRight/></Link></div></div><section className="about-studio"><div><span className="eyebrow">МЕСТО ВСТРЕЧИ</span><h2>MALABAR.</h2></div><div><p>Благовещенск<br/>Забурхановская, 102а<br/>2 этаж · серая дверь справа</p><a className="text-link" href={links.map} target="_blank" rel="noreferrer">Открыть карту <ArrowUpRight/></a></div></section></div>}
export function Prices(){return <div className="prices-page"><div className="page-heading"><div className="section-eyebrow"><span>СТОИМОСТЬ</span><span>ТВОЯ ИДЕЯ — ОТПРАВНАЯ ТОЧКА</span></div><TextAnimate>ЦЕНА ИДЕИ.</TextAnimate></div><section className="price-statement"><span className="price-number">01</span><div><h2>У КАЖДОЙ<br/>РАБОТЫ —<br/><i>свой масштаб.</i></h2><p>Размер, место, детализация и цвет влияют на стоимость. Пришли мне идею и референс — я назову цену твоей работы.</p><a href={links.vk} target="_blank" rel="noreferrer" className="text-link">Актуальный прайс в VK <ArrowUpRight/></a></div></section><div className="price-note"><span>ЧТО ПРИСЛАТЬ ДЛЯ ОЦЕНКИ</span><ol><li>Идею или референс</li><li>Место на теле</li><li>Размер в сантиметрах</li></ol><Button asChild><Link to="/booking">Узнать стоимость <ArrowUpRight size={20}/></Link></Button></div></div>}
const steps=[['01','IDEA','Всё начинается с «хочу».','Пришли идею, референсы, место и примерный размер. Можно начать с нескольких слов.'],['02','SKETCH','Находим твою линию.','Обсудим композицию, детали, стоимость и дату. Договоримся об эскизе до сеанса.'],['03','INK','Идея становится частью тебя.','Встретимся в студии, уточним расположение рисунка и приступим к работе.'],['04','HEAL','Забота — часть процесса.','После сеанса я объясню уход. Следуй рекомендациям и напиши мне, если появятся вопросы.']];
export function Process(){return <div className="process-page"><div className="page-heading"><span className="eyebrow">ОТ ЗАМЫСЛА ДО ЧЕРНИЛ</span><TextAnimate>ТВОЯ ИСТОРИЯ.</TextAnimate></div><div className="process-story">{steps.map(([n,en,title,body],i)=><section className="process-step" key={n}><div className="process-sticky"><span>{n} / 04</span><h2>{en}</h2><svg viewBox="0 0 500 40" className="pencil-line" aria-hidden="true"><motion.path d="M3 30 C100 15 190 29 280 20 S410 8 496 17" fill="none" stroke="currentColor" strokeWidth="1.5" initial={{pathLength:0}} whileInView={{pathLength:1}} viewport={{once:true}} transition={{duration:1.2}}/></svg></div><BlurFade className="process-body"><h3>{title}</h3><p>{body}</p>{i===2&&<img src={asset('assets/works/angel.webp')} alt="Детали авторской татуировки ORLICA" loading="lazy" width="480" height="640"/>}</BlurFade></section>)}</div><div className="process-end"><Link to="/booking" className="text-link">Начнём с твоей идеи <ArrowUpRight/></Link></div></div>}
const faqs=[['Сколько стоит татуировка?','Цена зависит от размера, места и сложности. Расскажи мне об идее и пришли референсы — я смогу оценить работу.'],['Можно прийти со своей идеей?','Да. Покажи, что тебе нравится: рисунки, фотографии, детали или просто опиши задумку. Вместе определим направление.'],['А если я ещё не знаю, что хочу?','Начни с работ, которые тебя цепляют. Собери пару примеров и напиши мне — обсудим направление и свободные эскизы.'],['Как выбрать размер и место?','Укажи примерные пожелания в заявке. Композицию и читаемость мелких деталей лучше обсудить с мастером до записи.'],['Как записаться?','Пройди короткую форму, выбери доступное время или обсуди дату в Telegram. Заявка становится записью после моего подтверждения.'],['Что взять на сеанс?','Референсы и удобную одежду, которая открывает выбранное место. Остальные детали подготовки уточни у меня перед встречей.'],['Как ухаживать за татуировкой?','После сеанса я дам рекомендации для твоей работы. Если что-то беспокоит, напиши мне; при выраженном ухудшении самочувствия обратись к врачу.'],['Где находится студия?','Malabar, Благовещенск, Забурхановская улица, 102а. Второй этаж, серая дверь справа. Приём по предварительной записи.']];
export function Faq(){return <div className="faq-page"><div className="page-heading"><span className="eyebrow">ПЕРЕД ПЕРВЫМ ШАГОМ</span><TextAnimate>ВОПРОСИКИ.</TextAnimate></div><div className="faq-layout"><p className="faq-aside">Всё, что хочется<br/>спросить <i>до.</i></p><Accordion type="single" collapsible>{faqs.map(([q,a],i)=><AccordionItem key={q} value={String(i)} title={q}><p>{a}</p></AccordionItem>)}</Accordion></div><a className="text-link faq-direct" href={links.telegram} target="_blank" rel="noreferrer">Спросить меня <ArrowUpRight/></a></div>}
export function NotFound(){return <section className="not-found"><span>404 / СТРАНИЦА НЕ НАЙДЕНА</span><h1>ПОТЕРЯЛИСЬ?</h1><Link to="/works" className="text-link">Вернуться к работам <ArrowUpRight/></Link></section>}
